# Generated by Django 5.0.4 on 2024-05-15 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'El número de teléfono debe tener 9 dígitos numéricos.')]),
        ),
    ]
