# Generated by Django 5.0.4 on 2024-05-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='info_adicional',
            field=models.TextField(),
        ),
    ]
