# Generated by Django 5.0.4 on 2024-05-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contacto_info_adicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='password_cliente',
        ),
    ]
