# Generated by Django 5.0.1 on 2024-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contacto_email_contacto_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptado')], default='P', max_length=1),
        ),
    ]
