# Generated by Django 5.0.1 on 2024-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reserva_mecanico'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='foto_mecanico',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
