# Generated by Django 5.0.4 on 2024-05-25 04:03

import core.funciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_mecanico_foto_mecanico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='foto_mecanico',
            field=models.ImageField(default=1, upload_to=core.funciones.upload_to_mecanicos),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='foto',
            field=models.ImageField(upload_to=core.funciones.upload_to_trabajos),
        ),
    ]
