# Generated by Django 5.0.4 on 2024-06-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_mecanico_foto_mecanico_alter_trabajo_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('servicio_1', models.CharField(choices=[('N', 'No'), ('S', 'Si')], default='N', max_length=1)),
                ('servicio_2', models.CharField(choices=[('N', 'No'), ('S', 'Si')], default='N', max_length=1)),
                ('servicio_3', models.CharField(choices=[('N', 'No'), ('S', 'Si')], default='N', max_length=1)),
                ('servicio_4', models.CharField(choices=[('N', 'No'), ('S', 'Si')], default='N', max_length=1)),
            ],
        ),
    ]
