# Generated by Django 5.0.4 on 2024-06-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='total_carrito',
            field=models.IntegerField(default=0),
        ),
    ]
