# Generated by Django 5.0.4 on 2024-06-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_carrito_total_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('id_pago', models.CharField(max_length=50)),
                ('id_pagador', models.CharField(max_length=50)),
                ('token_pago', models.CharField(max_length=50)),
                ('detalle_pago', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
