# Generated by Django 5.0.6 on 2024-06-21 13:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pago_reserva_remove_reserva_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='foto_mecanico',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
