# Generated by Django 5.0.4 on 2024-06-23 02:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_trabajo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
